# Generated by Django 3.0.3 on 2020-02-13 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_auto_20200212_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourse',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentlesson',
            name='student',
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentlesson',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='approval_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='approval_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentlesson',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
